package entities;
// Generated Jun 5, 2016 1:04:58 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TAddresses generated by hbm2java
 */
@Entity
@Table(name = "t_addresses", catalog = "testdb")
public class TAddresses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2941747040615460423L;
	
	private TAddressesId id;
	private TPeople TPeople;
	private String addrType;
	private String addrInfo;

	public TAddresses() {
	}

	public TAddresses(TAddressesId id, TPeople TPeople, String addrType) {
		this.id = id;
		this.TPeople = TPeople;
		this.addrType = addrType;
	}

	public TAddresses(TAddressesId id, TPeople TPeople, String addrType, String addrInfo) {
		this.id = id;
		this.TPeople = TPeople;
		this.addrType = addrType;
		this.addrInfo = addrInfo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false) ),
			@AttributeOverride(name = "TPeopleId", column = @Column(name = "T_PEOPLE_ID", nullable = false) ) })
	public TAddressesId getId() {
		return this.id;
	}

	public void setId(TAddressesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_PEOPLE_ID", nullable = false, insertable = false, updatable = false)
	public TPeople getTPeople() {
		return this.TPeople;
	}

	public void setTPeople(TPeople TPeople) {
		this.TPeople = TPeople;
	}

	@Column(name = "ADDR_TYPE", nullable = false, length = 5)
	public String getAddrType() {
		return this.addrType;
	}

	public void setAddrType(String addrType) {
		this.addrType = addrType;
	}

	@Column(name = "ADDR_INFO", length = 300)
	public String getAddrInfo() {
		return this.addrInfo;
	}

	public void setAddrInfo(String addrInfo) {
		this.addrInfo = addrInfo;
	}

}
