package entities;
// Generated Jun 5, 2016 1:04:58 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TMail generated by hbm2java
 */
@Entity
@Table(name = "t_mail", catalog = "testdb")
public class TMail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4573163355801024829L;
	
	private TMailId id;
	private TPeople TPeople;
	private String emailType;
	private String email;

	public TMail() {
	}

	public TMail(TMailId id, TPeople TPeople, String emailType) {
		this.id = id;
		this.TPeople = TPeople;
		this.emailType = emailType;
	}

	public TMail(TMailId id, TPeople TPeople, String emailType, String email) {
		this.id = id;
		this.TPeople = TPeople;
		this.emailType = emailType;
		this.email = email;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false) ),
			@AttributeOverride(name = "TPeopleId", column = @Column(name = "T_PEOPLE_ID", nullable = false) ) })
	public TMailId getId() {
		return this.id;
	}

	public void setId(TMailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_PEOPLE_ID", nullable = false, insertable = false, updatable = false)
	public TPeople getTPeople() {
		return this.TPeople;
	}

	public void setTPeople(TPeople TPeople) {
		this.TPeople = TPeople;
	}

	@Column(name = "EMAIL_TYPE", nullable = false, length = 5)
	public String getEmailType() {
		return this.emailType;
	}

	public void setEmailType(String emailType) {
		this.emailType = emailType;
	}

	@Column(name = "EMAIL", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
