package entities;
// Generated Jun 5, 2016 1:04:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPeople generated by hbm2java
 */
@Entity
@Table(name = "t_people", catalog = "testdb")
public class TPeople implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2701987918140713350L;
	
	private Integer id;
	private String fullName;
	private String pin;
	private Set<TAddresses> TAddresseses = new HashSet<TAddresses>(0);
	private Set<TAddresses> TAddresseses_1 = new HashSet<TAddresses>(0);
	private Set<TMail> TMails = new HashSet<TMail>(0);
	private Set<TMail> TMails_1 = new HashSet<TMail>(0);

	public TPeople() {
	}

	public TPeople(String fullName) {
		this.fullName = fullName;
	}

	public TPeople(String fullName, String pin, Set<TAddresses> TAddresseses, Set<TAddresses> TAddresseses_1,
			Set<TMail> TMails, Set<TMail> TMails_1) {
		this.fullName = fullName;
		this.pin = pin;
		this.TAddresseses = TAddresseses;
		this.TAddresseses_1 = TAddresseses_1;
		this.TMails = TMails;
		this.TMails_1 = TMails_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "FULL_NAME", nullable = false, length = 90)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "PIN", length = 10)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPeople")
	public Set<TAddresses> getTAddresseses() {
		return this.TAddresseses;
	}

	public void setTAddresseses(Set<TAddresses> TAddresseses) {
		this.TAddresseses = TAddresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPeople")
	public Set<TAddresses> getTAddresseses_1() {
		return this.TAddresseses_1;
	}

	public void setTAddresseses_1(Set<TAddresses> TAddresseses_1) {
		this.TAddresseses_1 = TAddresseses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPeople")
	public Set<TMail> getTMails() {
		return this.TMails;
	}

	public void setTMails(Set<TMail> TMails) {
		this.TMails = TMails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPeople")
	public Set<TMail> getTMails_1() {
		return this.TMails_1;
	}

	public void setTMails_1(Set<TMail> TMails_1) {
		this.TMails_1 = TMails_1;
	}

}
